name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint 
      - name: Run Build
        run: npm run build
      - name: Run Migrations
        run: npm run migration:run
        env:
          DATABASE_USERNAME: patientuser
          DATABASE_PASSWORD: patient
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          DATABASE_NAME: patientdb
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}